[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "priority-expiry-cache"
version = "0.0.2"

[tool.setuptools.packages.find]
include = ["priority_expiry"]